import { useState } from "react";
import { ArrowUpRight, CalendarDays, Check, ChevronRight, Circle, Plus, Sparkles } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { PageHeader } from "@/components/common/page-header";
import { cn } from "@/lib/utils";
import { dsaActivity, focusTasks as initialFocus, jobStages, learning, projects, stats, weeklyActivity } from "@/data/dashboard";

const statTone = { blue: "bg-info/10 text-info", green: "bg-success/10 text-success", amber: "bg-warning/10 text-warning", violet: "bg-primary/10 text-primary" };
const priorityTone = { High: "border-danger/20 bg-danger/10 text-danger", Medium: "border-warning/20 bg-warning/10 text-warning", Low: "border-info/20 bg-info/10 text-info" };

export function DashboardContent() {
  const [focus, setFocus] = useState(initialFocus); const done = focus.filter((task) => task.completed).length; const progress = Math.round((done / focus.length) * 100);
  const comingSoon = (label: string) => toast(`${label} is coming next`, { description: "This action will connect to your Spring Boot API." });
  return <div className="space-y-6 animate-page-in"><PageHeader title="Good evening, Raj 👋" description="Here’s your development activity at a glance." action={<div className="flex h-9 items-center gap-2 rounded-md border border-border bg-card px-3 text-sm text-muted-foreground"><CalendarDays className="size-4" />Sep 23, 2026</div>} />
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4" aria-label="Weekly statistics">{stats.map((stat) => <Card key={stat.label} className="group transition-all hover:-translate-y-0.5 hover:border-primary/25 hover:shadow-card"><CardContent className="p-5"><div className="flex items-start justify-between"><span className={cn("grid size-10 place-items-center rounded-md", statTone[stat.tone])}><stat.icon className="size-5" /></span><ArrowUpRight className="size-4 text-muted-foreground opacity-0 transition-opacity group-hover:opacity-100" /></div><p className="mt-5 text-sm text-muted-foreground">{stat.label}</p><div className="mt-1 flex items-end justify-between gap-3"><p className="font-display text-3xl font-semibold">{stat.value}</p><p className="pb-1 text-xs font-medium text-success">{stat.change}</p></div></CardContent></Card>)}</section>
    <div className="grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><Card><CardHeader className="flex-row items-start justify-between space-y-0"><div><CardTitle>Today’s Focus</CardTitle><p className="mt-1 text-sm text-muted-foreground">Keep the important work moving.</p></div><Button size="sm" onClick={() => comingSoon("Add task")}><Plus />Add task</Button></CardHeader><CardContent><div className="mb-5 flex items-center gap-4"><Progress value={progress} /><span className="shrink-0 text-xs font-medium text-muted-foreground">{done}/{focus.length} complete</span></div><div className="divide-y divide-border">{focus.map((task) => <div key={task.id} className="flex items-center gap-3 py-3.5"><button onClick={() => setFocus((items) => items.map((item) => item.id === task.id ? { ...item, completed: !item.completed } : item))} className={cn("grid size-5 shrink-0 place-items-center rounded border transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring", task.completed ? "border-primary bg-primary text-primary-foreground" : "border-input hover:border-primary")} aria-label={`${task.completed ? "Mark incomplete" : "Mark complete"}: ${task.title}`}>{task.completed && <Check className="size-3.5" />}</button><span className={cn("min-w-0 flex-1 text-sm", task.completed && "text-muted-foreground line-through")}>{task.title}</span><Badge variant="outline" className={priorityTone[task.priority]}>{task.priority}</Badge></div>)}</div></CardContent></Card>
      <Card><CardHeader><div className="flex items-center justify-between"><div><CardTitle>Weekly Activity</CardTitle><p className="mt-1 text-sm text-muted-foreground">Problems solved by day</p></div><Badge variant="outline" className="border-success/20 bg-success/10 text-success">+18%</Badge></div></CardHeader><CardContent><div className="flex h-44 items-end gap-3" aria-label="Static weekly activity chart">{weeklyActivity.map((height, index) => <div key={index} className="flex flex-1 flex-col items-center gap-2"><div className="flex h-32 w-full items-end"><div className="w-full rounded-sm bg-primary/20 transition-colors hover:bg-primary" style={{ height: `${height}%` }} /></div><span className="text-[11px] text-muted-foreground">{["M","T","W","T","F","S","S"][index]}</span></div>)}</div></CardContent></Card></div>
    <div className="grid gap-6 xl:grid-cols-2"><Card><CardHeader className="flex-row items-center justify-between space-y-0"><div><CardTitle>Recent DSA Activity</CardTitle><p className="mt-1 text-sm text-muted-foreground">Latest problem-solving work</p></div><Button variant="ghost" size="sm" onClick={() => comingSoon("DSA tracker")}>View all<ChevronRight /></Button></CardHeader><CardContent className="overflow-x-auto"><table className="w-full min-w-[440px] text-left text-sm"><thead><tr className="border-b border-border text-xs text-muted-foreground"><th className="pb-3 font-medium">Problem</th><th className="pb-3 font-medium">Difficulty</th><th className="pb-3 text-right font-medium">Status</th></tr></thead><tbody>{dsaActivity.map((item) => <tr key={item.problem} className="border-b border-border last:border-0"><td className="py-3.5 font-medium">{item.problem}</td><td className="py-3.5"><Badge variant="outline" className={item.difficulty === "Easy" ? "border-success/20 bg-success/10 text-success" : "border-warning/20 bg-warning/10 text-warning"}>{item.difficulty}</Badge></td><td className="py-3.5 text-right"><span className={cn("inline-flex items-center gap-1.5 text-xs", item.status === "Solved" ? "text-success" : "text-warning")}><Circle className="size-1.5 fill-current" />{item.status}</span></td></tr>)}</tbody></table></CardContent></Card>
      <Card><CardHeader><CardTitle>Learning Progress</CardTitle><p className="text-sm text-muted-foreground">Current skill development</p></CardHeader><CardContent className="space-y-5">{learning.map((skill) => <div key={skill.name}><div className="mb-2 flex justify-between text-sm"><span className="font-medium">{skill.name}</span><span className="font-mono text-xs text-muted-foreground">{skill.value}%</span></div><Progress value={skill.value} /></div>)}</CardContent></Card></div>
    <div className="grid gap-6 lg:grid-cols-[.75fr_1.25fr]"><Card><CardHeader><CardTitle>Job Applications</CardTitle><p className="text-sm text-muted-foreground">Current pipeline snapshot</p></CardHeader><CardContent className="space-y-3">{jobStages.map((stage) => <div key={stage.label} className="flex items-center rounded-md border border-border bg-surface-subtle p-3"><span className={cn("mr-3 size-2 rounded-full", stage.tone)} /><span className="flex-1 text-sm text-muted-foreground">{stage.label}</span><span className="font-display text-lg font-semibold">{stage.value}</span></div>)}</CardContent></Card>
      <Card><CardHeader className="flex-row items-center justify-between space-y-0"><div><CardTitle>Current Projects</CardTitle><p className="mt-1 text-sm text-muted-foreground">What you’re actively building</p></div><Button variant="ghost" size="sm" onClick={() => comingSoon("Projects")}>View all<ChevronRight /></Button></CardHeader><CardContent className="grid gap-4 md:grid-cols-3">{projects.map((project) => <div key={project.name} className="rounded-md border border-border bg-surface-subtle p-4 transition-colors hover:border-primary/25"><div className="flex items-start justify-between"><h3 className="font-display font-semibold">{project.name}</h3><span className="font-mono text-xs text-muted-foreground">{project.progress}%</span></div><div className="mt-3 flex min-h-12 flex-wrap content-start gap-1.5">{project.stack.map((tech) => <Badge key={tech} variant="secondary" className="font-normal">{tech}</Badge>)}</div><Progress className="mt-4" value={project.progress} /></div>)}</CardContent></Card></div>
    <Card><CardHeader><CardTitle className="flex items-center gap-2"><Sparkles className="size-4 text-primary" />Quick actions</CardTitle></CardHeader><CardContent className="grid gap-2 sm:grid-cols-2 lg:grid-cols-5">{["Add DSA Problem","Add Job Application","Add Learning Topic","Add Task","Add Project"].map((label) => <Button key={label} variant="outline" className="justify-start" onClick={() => comingSoon(label)}><Plus />{label}</Button>)}</CardContent></Card>
  </div>;
}
