import { useState, type FormEvent } from "react";
import { Link } from "@tanstack/react-router";
import { ArrowRight, Loader2, Mail } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { PasswordField } from "./password-field";

export function LoginForm() { const [errors, setErrors] = useState<Record<string,string>>({}); const [submitting, setSubmitting] = useState(false); const [message, setMessage] = useState("");
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); const email = String(data.get("email") ?? ""); const password = String(data.get("password") ?? ""); const next: Record<string,string> = {}; if (!/^\S+@\S+\.\S+$/.test(email)) next["email"] = "Enter a valid email address."; if (!password) next["password"] = "Password is required."; setErrors(next); if (!Object.keys(next).length) { setSubmitting(true); window.setTimeout(() => { setSubmitting(false); setMessage("Your Spring Boot authentication service is not connected yet."); }, 500); } };
  return <><div className="mb-8"><p className="mb-3 font-mono text-xs text-primary">// WELCOME_BACK</p><h1 className="font-display text-3xl font-semibold">Sign in to DevCommand</h1><p className="mt-2 text-sm text-muted-foreground">Continue managing your developer journey.</p></div><form onSubmit={submit} noValidate className="space-y-5"><div className="space-y-2"><Label htmlFor="email">Email</Label><div className="relative"><Mail className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input id="email" name="email" type="email" autoComplete="email" className="pl-9" placeholder="raj@example.com" aria-invalid={!!errors["email"]} /></div>{errors["email"] && <p className="text-xs text-danger">{errors["email"]}</p>}</div><div className="space-y-2"><div className="flex justify-between"><Label htmlFor="password">Password</Label><button type="button" onClick={() => setMessage("Password reset will be available when authentication is connected.")} className="text-xs text-primary hover:underline">Forgot password?</button></div><PasswordField id="password" name="password" autoComplete="current-password" placeholder="Enter your password" aria-invalid={!!errors["password"]} />{errors["password"] && <p className="text-xs text-danger">{errors["password"]}</p>}</div><Button className="h-11 w-full" type="submit" disabled={submitting}>{submitting ? <Loader2 className="animate-spin" /> : <>Login<ArrowRight /></>}</Button>{message && <p role="status" className="rounded-md border border-info/20 bg-info/10 p-3 text-sm text-info">{message}</p>}</form><p className="mt-7 text-center text-sm text-muted-foreground">Don’t have an account? <Link to="/register" className="font-medium text-primary hover:underline">Create one</Link></p></>;
}
